eval "$(starship init zsh)"

HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY

alias cat="bat"
alias ls="eza --icons -a --group-directories-first -1"
alias ll="eza --icons -a --group-directories-first -1 --no-user --long"
alias tree="eza --icons --tree --group-directories-first"
alias vim="nvim"
alias grep="rg"
alias find="fd"
